<?php
App::uses('AppController', 'Controller');
/**
 * Ages Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property Age $Age
 */
class AgesController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->Age->recursive = 0;
		$this->set('ages', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->Age->exists($id)) {
			throw new NotFoundException(__('Invalid age'));
		}
		$options = array('conditions' => array('Age.' . $this->Age->primaryKey => $id));
		$this->set('age', $this->Age->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->Age->create();
			if ($this->Age->save($this->request->data)) {
				$this->Session->setFlash(__('The age has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The age could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->Age->exists($id)) {
			throw new NotFoundException(__('Invalid age'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->Age->save($this->request->data)) {
				$this->Session->setFlash(__('The age has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The age could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('Age.' . $this->Age->primaryKey => $id));
			$this->request->data = $this->Age->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->Age->id = $id;
		if (!$this->Age->exists()) {
			throw new NotFoundException(__('Invalid age'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->Age->delete()) {
			$this->Session->setFlash(__('The age has been deleted.'));
		} else {
			$this->Session->setFlash(__('The age could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
