<?php
App::uses('AppController', 'Controller');
/**
 * Ages Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property Age $Age
 */
class AjaxController extends AppController {
    
    
     var $uses = array('Competition', 'CompetitionsProfession','CompetitionsCandidate','CompetitionsReferee') ;
     
     
    public function index() {
        
    } 
     
     public function beforeFilter() {
        if(!session_id()) session_start();
        parent::beforeFilter();             
        $this->Auth->allow('proccessAjaxRequest');
     
     }
     
     public function proccessAjaxRequest($action,$ajaxAction) {
      
        $data = $_POST['data'];
      //  echo $ajaxAction;
        switch ($ajaxAction) {
            
           case "competitionAddProfession":
               
               $competitionId = $data['competition_id'] ;
               $this->layout = false;
               $this->CompetitionsProfession->create();
               $this->CompetitionsProfession->save($data);
               $competition = $this->Competition->findById($competitionId);
               $this->set('competition',$competition);
               echo $this->render('/Elements/competitions_professions');
               die(); 
               break;

           case "competitionAddCandidate":
               
               $competitionId = $data['competition_id'] ;
               $this->layout = false;
               $this->CompetitionsCandidate->create();
               $this->CompetitionsCandidate->save($data);
               $competition = $this->Competition->findById($competitionId);
               $this->set('competition',$competition);
               echo $this->render('/Elements/competition_candidates');
               die(); 
               break;
               
          case "competitionAddReferee":
               
               $competitionId = $data['competition_id'] ;
               $this->layout = false;
               $this->CompetitionsReferee->create();
               $this->CompetitionsReferee->save($data);
               $competition = $this->Competition->findById($competitionId);
               $this->set('competition',$competition);
               echo $this->render('/Elements/competition_referees');
               die(); 
               break;               
            
            
        }
        
        die("end");
        
 
        
	}

}
