<?php
App::uses('AppController', 'Controller');
/**
 * AssociationsHistories Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property AssociationsHistory $AssociationsHistory
 */
class AssociationsHistoriesController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->AssociationsHistory->recursive = 0;
		$this->set('associationsHistories', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->AssociationsHistory->exists($id)) {
			throw new NotFoundException(__('Invalid associations history'));
		}
		$options = array('conditions' => array('AssociationsHistory.' . $this->AssociationsHistory->primaryKey => $id));
		$this->set('associationsHistory', $this->AssociationsHistory->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->AssociationsHistory->create();
			if ($this->AssociationsHistory->save($this->request->data)) {
				$this->Session->setFlash(__('The associations history has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The associations history could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->AssociationsHistory->exists($id)) {
			throw new NotFoundException(__('Invalid associations history'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->AssociationsHistory->save($this->request->data)) {
				$this->Session->setFlash(__('The associations history has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The associations history could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('AssociationsHistory.' . $this->AssociationsHistory->primaryKey => $id));
			$this->request->data = $this->AssociationsHistory->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->AssociationsHistory->id = $id;
		if (!$this->AssociationsHistory->exists()) {
			throw new NotFoundException(__('Invalid associations history'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->AssociationsHistory->delete()) {
			$this->Session->setFlash(__('The associations history has been deleted.'));
		} else {
			$this->Session->setFlash(__('The associations history could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
