<?php
App::uses('AppController', 'Controller');
/**
 * AthletsMedicalTests Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property AthletsMedicalTest $AthletsMedicalTest
 */
class AthletsMedicalTestsController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->AthletsMedicalTest->recursive = 0;
		$this->set('AthletsMedicalTests', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->AthletsMedicalTest->exists($id)) {
			throw new NotFoundException(__('Invalid Athlets medical test'));
		}
		$options = array('conditions' => array('AthletsMedicalTest.' . $this->AthletsMedicalTest->primaryKey => $id));
		$this->set('AthletsMedicalTest', $this->AthletsMedicalTest->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->AthletsMedicalTest->create();
			if ($this->AthletsMedicalTest->save($this->request->data)) {
				$this->Session->setFlash(__('The Athlets medical test has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The Athlets medical test could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->AthletsMedicalTest->exists($id)) {
			throw new NotFoundException(__('Invalid Athlets medical test'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->AthletsMedicalTest->save($this->request->data)) {
				$this->Session->setFlash(__('The Athlets medical test has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The Athlets medical test could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('AthletsMedicalTest.' . $this->AthletsMedicalTest->primaryKey => $id));
			$this->request->data = $this->AthletsMedicalTest->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->AthletsMedicalTest->id = $id;
		if (!$this->AthletsMedicalTest->exists()) {
			throw new NotFoundException(__('Invalid Athlets medical test'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->AthletsMedicalTest->delete()) {
			$this->Session->setFlash(__('The Athlets medical test has been deleted.'));
		} else {
			$this->Session->setFlash(__('The Athlets medical test could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
