<?php
App::uses('AppController', 'Controller');
/**
 * ChestNumbers Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property ChestNumber $ChestNumber
 */
class ChestNumbersController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->ChestNumber->recursive = 0;
		$this->set('chestNumbers', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->ChestNumber->exists($id)) {
			throw new NotFoundException(__('Invalid chest number'));
		}
		$options = array('conditions' => array('ChestNumber.' . $this->ChestNumber->primaryKey => $id));
		$this->set('chestNumber', $this->ChestNumber->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->ChestNumber->create();
			if ($this->ChestNumber->save($this->request->data)) {
				$this->Session->setFlash(__('The chest number has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The chest number could not be saved. Please, try again.'));
			}
		}
		$Athlets = $this->ChestNumber->Athlete->find('list');
		$this->set(compact('Athlets'));
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->ChestNumber->exists($id)) {
			throw new NotFoundException(__('Invalid chest number'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->ChestNumber->save($this->request->data)) {
				$this->Session->setFlash(__('The chest number has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The chest number could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('ChestNumber.' . $this->ChestNumber->primaryKey => $id));
			$this->request->data = $this->ChestNumber->find('first', $options);
		}
		$Athlets = $this->ChestNumber->Athlete->find('list');
		$this->set(compact('Athlets'));
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->ChestNumber->id = $id;
		if (!$this->ChestNumber->exists()) {
			throw new NotFoundException(__('Invalid chest number'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->ChestNumber->delete()) {
			$this->Session->setFlash(__('The chest number has been deleted.'));
		} else {
			$this->Session->setFlash(__('The chest number could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
