<?php
App::uses('AppController', 'Controller');
/**
 * Coachers Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property Coacher $Coacher
 */
class CoachersController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->Coacher->recursive = 0;
		$this->set('coachers', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->Coacher->exists($id)) {
			throw new NotFoundException(__('Invalid coacher'));
		}
		$options = array('conditions' => array('Coacher.' . $this->Coacher->primaryKey => $id));
		$this->set('coacher', $this->Coacher->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->Coacher->create();
			if ($this->Coacher->save($this->request->data)) {
				$this->Session->setFlash(__('The coacher has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The coacher could not be saved. Please, try again.'));
			}
		}
		$associations = $this->Coacher->Association->find('list');
		$this->set(compact('associations'));
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->Coacher->exists($id)) {
			throw new NotFoundException(__('Invalid coacher'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->Coacher->save($this->request->data)) {
				$this->Session->setFlash(__('The coacher has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The coacher could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('Coacher.' . $this->Coacher->primaryKey => $id));
			$this->request->data = $this->Coacher->find('first', $options);
		}
		$associations = $this->Coacher->Association->find('list');
        $accountings = $this->Coacher->Accounting->findAllByIdentityNumberAndEntityType($id,'Athlet');
        $remarksAry = $this->Coacher->Remarks->findAllByIdentityNumberAndEntityType($id,'Athlet');
        // fix remarks array to suit remarks element
        foreach ($remarksAry as $key => $remark) {
            $remarks[] = $remark['Remarks']; 
        }
        //print_r($accountings);
        $this->set(compact('associations','remarks','accountings','athlets'));
        $this->set('data',$this->data['Coacher']);
        $this->set('addresses',$this->data['Coacher']['Address']);
        $this->set('athlets',$this->data['Coacher']['Athlet']);
        // for remarks we expose entity type
        $this->set('entity_type','Coacher');
        
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->Coacher->id = $id;
		if (!$this->Coacher->exists()) {
			throw new NotFoundException(__('Invalid coacher'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->Coacher->delete()) {
			$this->Session->setFlash(__('The coacher has been deleted.'));
		} else {
			$this->Session->setFlash(__('The coacher could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
