<?php
App::uses('AppController', 'Controller');
/**
 * CompetitionsHeats Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property CompetitionsHeat $CompetitionsHeat
 */
class CompetitionsHeatsController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->CompetitionsHeat->recursive = 0;
		$this->set('competitionsHeats', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->CompetitionsHeat->exists($id)) {
			throw new NotFoundException(__('Invalid competitions heat'));
		}
		$options = array('conditions' => array('CompetitionsHeat.' . $this->CompetitionsHeat->primaryKey => $id));
		$this->set('competitionsHeat', $this->CompetitionsHeat->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->CompetitionsHeat->create();
			if ($this->CompetitionsHeat->save($this->request->data)) {
				$this->Session->setFlash(__('The competitions heat has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The competitions heat could not be saved. Please, try again.'));
			}
		}
		$professions = $this->CompetitionsHeat->Profession->find('list');
		$this->set(compact('professions'));
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->CompetitionsHeat->exists($id)) {
			throw new NotFoundException(__('Invalid competitions heat'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->CompetitionsHeat->save($this->request->data)) {
				$this->Session->setFlash(__('The competitions heat has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The competitions heat could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('CompetitionsHeat.' . $this->CompetitionsHeat->primaryKey => $id));
			$this->request->data = $this->CompetitionsHeat->find('first', $options);
		}
		$professions = $this->CompetitionsHeat->Profession->find('list');
		$this->set(compact('professions'));
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->CompetitionsHeat->id = $id;
		if (!$this->CompetitionsHeat->exists()) {
			throw new NotFoundException(__('Invalid competitions heat'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->CompetitionsHeat->delete()) {
			$this->Session->setFlash(__('The competitions heat has been deleted.'));
		} else {
			$this->Session->setFlash(__('The competitions heat could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
