<?php
App::uses('AppController', 'Controller');
/**
 * CompetitionsCandidates Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property CompetitionsCandidate $CompetitionsCandidate
 */
class CompetitionsCandidatesController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->CompetitionsCandidate->recursive = 0;
		$this->set('competitionsCandidates', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->CompetitionsCandidate->exists($id)) {
			throw new NotFoundException(__('Invalid competitions candidate'));
		}
		$options = array('conditions' => array('CompetitionsCandidate.' . $this->CompetitionsCandidate->primaryKey => $id));
		$this->set('competitionsCandidate', $this->CompetitionsCandidate->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->CompetitionsCandidate->create();
			if ($this->CompetitionsCandidate->save($this->request->data)) {
				$this->Session->setFlash(__('The competitions candidate has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The competitions candidate could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->CompetitionsCandidate->exists($id)) {
			throw new NotFoundException(__('Invalid competitions candidate'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->CompetitionsCandidate->save($this->request->data)) {
				$this->Session->setFlash(__('The competitions candidate has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The competitions candidate could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('CompetitionsCandidate.' . $this->CompetitionsCandidate->primaryKey => $id));
			$this->request->data = $this->CompetitionsCandidate->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->CompetitionsCandidate->id = $id;
		if (!$this->CompetitionsCandidate->exists()) {
			throw new NotFoundException(__('Invalid competitions candidate'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->CompetitionsCandidate->delete()) {
			$this->Session->setFlash(__('The competitions candidate has been deleted.'));
		} else {
			$this->Session->setFlash(__('The competitions candidate could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
