<?php
App::uses('AppController', 'Controller');
/**
 * CompetitionsReferees Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property CompetitionsReferee $CompetitionsReferee
 */
class CompetitionsRefereesController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->CompetitionsReferee->recursive = 0;
		$this->set('competitionsReferees', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->CompetitionsReferee->exists($id)) {
			throw new NotFoundException(__('Invalid competitions referee'));
		}
		$options = array('conditions' => array('CompetitionsReferee.' . $this->CompetitionsReferee->primaryKey => $id));
		$this->set('competitionsReferee', $this->CompetitionsReferee->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->CompetitionsReferee->create();
			if ($this->CompetitionsReferee->save($this->request->data)) {
				$this->Session->setFlash(__('The competitions referee has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The competitions referee could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->CompetitionsReferee->exists($id)) {
			throw new NotFoundException(__('Invalid competitions referee'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->CompetitionsReferee->save($this->request->data)) {
				$this->Session->setFlash(__('The competitions referee has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The competitions referee could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('CompetitionsReferee.' . $this->CompetitionsReferee->primaryKey => $id));
			$this->request->data = $this->CompetitionsReferee->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->CompetitionsReferee->id = $id;
		if (!$this->CompetitionsReferee->exists()) {
			throw new NotFoundException(__('Invalid competitions referee'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->CompetitionsReferee->delete()) {
			$this->Session->setFlash(__('The competitions referee has been deleted.'));
		} else {
			$this->Session->setFlash(__('The competitions referee could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
