<?php
App::uses('AppController', 'Controller');
/**
 * CompetitionsResults Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property CompetitionsResult $CompetitionsResult
 */
class CompetitionsResultsController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->CompetitionsResult->recursive = 0;
		$this->set('competitionsResults', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->CompetitionsResult->exists($id)) {
			throw new NotFoundException(__('Invalid competitions result'));
		}
		$options = array('conditions' => array('CompetitionsResult.' . $this->CompetitionsResult->primaryKey => $id));
		$this->set('competitionsResult', $this->CompetitionsResult->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->CompetitionsResult->create();
			if ($this->CompetitionsResult->save($this->request->data)) {
				$this->Session->setFlash(__('The competitions result has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The competitions result could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->CompetitionsResult->exists($id)) {
			throw new NotFoundException(__('Invalid competitions result'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->CompetitionsResult->save($this->request->data)) {
				$this->Session->setFlash(__('The competitions result has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The competitions result could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('CompetitionsResult.' . $this->CompetitionsResult->primaryKey => $id));
			$this->request->data = $this->CompetitionsResult->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->CompetitionsResult->id = $id;
		if (!$this->CompetitionsResult->exists()) {
			throw new NotFoundException(__('Invalid competitions result'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->CompetitionsResult->delete()) {
			$this->Session->setFlash(__('The competitions result has been deleted.'));
		} else {
			$this->Session->setFlash(__('The competitions result could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
