<?php
App::uses('AppController', 'Controller');
/**
 * Leages Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property Leage $Leage
 */
class LeagesController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->Leage->recursive = 0;
		$this->set('leages', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->Leage->exists($id)) {
			throw new NotFoundException(__('Invalid leage'));
		}
		$options = array('conditions' => array('Leage.' . $this->Leage->primaryKey => $id));
		$this->set('leage', $this->Leage->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->Leage->create();
			if ($this->Leage->save($this->request->data)) {
				$this->Session->setFlash(__('The leage has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The leage could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->Leage->exists($id)) {
			throw new NotFoundException(__('Invalid leage'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->Leage->save($this->request->data)) {
				$this->Session->setFlash(__('The leage has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The leage could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('Leage.' . $this->Leage->primaryKey => $id));
			$this->request->data = $this->Leage->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->Leage->id = $id;
		if (!$this->Leage->exists()) {
			throw new NotFoundException(__('Invalid leage'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->Leage->delete()) {
			$this->Session->setFlash(__('The leage has been deleted.'));
		} else {
			$this->Session->setFlash(__('The leage could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
