<?php
App::uses('AppController', 'Controller');
/**
 * ModelsFieldsMetaData Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property ModelsFieldsMetaDatum $ModelsFieldsMetaDatum
 */
class ModelsFieldsMetaDataController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->ModelsFieldsMetaDatum->recursive = 0;
		$this->set('modelsFieldsMetaData', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->ModelsFieldsMetaDatum->exists($id)) {
			throw new NotFoundException(__('Invalid models fields meta datum'));
		}
		$options = array('conditions' => array('ModelsFieldsMetaDatum.' . $this->ModelsFieldsMetaDatum->primaryKey => $id));
		$this->set('modelsFieldsMetaDatum', $this->ModelsFieldsMetaDatum->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->ModelsFieldsMetaDatum->create();
			if ($this->ModelsFieldsMetaDatum->save($this->request->data)) {
				$this->Session->setFlash(__('The models fields meta datum has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The models fields meta datum could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->ModelsFieldsMetaDatum->exists($id)) {
			throw new NotFoundException(__('Invalid models fields meta datum'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->ModelsFieldsMetaDatum->save($this->request->data)) {
				$this->Session->setFlash(__('The models fields meta datum has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The models fields meta datum could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('ModelsFieldsMetaDatum.' . $this->ModelsFieldsMetaDatum->primaryKey => $id));
			$this->request->data = $this->ModelsFieldsMetaDatum->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->ModelsFieldsMetaDatum->id = $id;
		if (!$this->ModelsFieldsMetaDatum->exists()) {
			throw new NotFoundException(__('Invalid models fields meta datum'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->ModelsFieldsMetaDatum->delete()) {
			$this->Session->setFlash(__('The models fields meta datum has been deleted.'));
		} else {
			$this->Session->setFlash(__('The models fields meta datum could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
