<?php
App::uses('AppController', 'Controller');
/**
 * PointsTables Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property PointsTable $PointsTable
 */
class PointsTablesController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->PointsTable->recursive = 0;
		$this->set('pointsTables', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->PointsTable->exists($id)) {
			throw new NotFoundException(__('Invalid points table'));
		}
		$options = array('conditions' => array('PointsTable.' . $this->PointsTable->primaryKey => $id));
		$this->set('pointsTable', $this->PointsTable->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->PointsTable->create();
			if ($this->PointsTable->save($this->request->data)) {
				$this->Session->setFlash(__('The points table has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The points table could not be saved. Please, try again.'));
			}
		}
		$professions = $this->PointsTable->Profession->find('list');
		$this->set(compact('professions'));
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->PointsTable->exists($id)) {
			throw new NotFoundException(__('Invalid points table'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->PointsTable->save($this->request->data)) {
				$this->Session->setFlash(__('The points table has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The points table could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('PointsTable.' . $this->PointsTable->primaryKey => $id));
			$this->request->data = $this->PointsTable->find('first', $options);
		}
		$professions = $this->PointsTable->Profession->find('list');
		$this->set(compact('professions'));
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->PointsTable->id = $id;
		if (!$this->PointsTable->exists()) {
			throw new NotFoundException(__('Invalid points table'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->PointsTable->delete()) {
			$this->Session->setFlash(__('The points table has been deleted.'));
		} else {
			$this->Session->setFlash(__('The points table could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
