<?php
App::uses('AppController', 'Controller');
/**
 * RefereesStudies Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property RefereesStudy $RefereesStudy
 */
class RefereesStudiesController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->RefereesStudy->recursive = 0;
		$this->set('refereesStudies', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param string id
 * @return void
 */
	public function view($id = null) {
		if (!$this->RefereesStudy->exists($id)) {
			throw new NotFoundException(__('Invalid referees study'));
		}
		$options = array('conditions' => array('RefereesStudy.' . $this->RefereesStudy->primaryKey => $id));
		$this->set('refereesStudy', $this->RefereesStudy->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->RefereesStudy->create();
			if ($this->RefereesStudy->save($this->request->data)) {
				$this->Session->setFlash(__('The referees study has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The referees study could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param string id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->RefereesStudy->exists($id)) {
			throw new NotFoundException(__('Invalid referees study'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->RefereesStudy->save($this->request->data)) {
				$this->Session->setFlash(__('The referees study has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The referees study could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('RefereesStudy.' . $this->RefereesStudy->primaryKey => $id));
			$this->request->data = $this->RefereesStudy->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param string id
 * @return void
 */
	public function delete($id = null) {
		$this->RefereesStudy->id = $id;
		if (!$this->RefereesStudy->exists()) {
			throw new NotFoundException(__('Invalid referees study'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->RefereesStudy->delete()) {
			$this->Session->setFlash(__('The referees study has been deleted.'));
		} else {
			$this->Session->setFlash(__('The referees study could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
