<?php
App::uses('AppController', 'Controller');
/**
 * RefereesLevels Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property RefereesLevel $RefereesLevel
 */
class RefereesLevelsController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->RefereesLevel->recursive = 0;
		$this->set('refereesLevels', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param string id
 * @return void
 */
	public function view($id = null) {
		if (!$this->RefereesLevel->exists($id)) {
			throw new NotFoundException(__('Invalid referees level'));
		}
		$options = array('conditions' => array('RefereesLevel.' . $this->RefereesLevel->primaryKey => $id));
		$this->set('refereesLevel', $this->RefereesLevel->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->RefereesLevel->create();
			if ($this->RefereesLevel->save($this->request->data)) {
				$this->Session->setFlash(__('The referees level has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The referees level could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param string id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->RefereesLevel->exists($id)) {
			throw new NotFoundException(__('Invalid referees level'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->RefereesLevel->save($this->request->data)) {
				$this->Session->setFlash(__('The referees level has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The referees level could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('RefereesLevel.' . $this->RefereesLevel->primaryKey => $id));
			$this->request->data = $this->RefereesLevel->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param string id
 * @return void
 */
	public function delete($id = null) {
		$this->RefereesLevel->id = $id;
		if (!$this->RefereesLevel->exists()) {
			throw new NotFoundException(__('Invalid referees level'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->RefereesLevel->delete()) {
			$this->Session->setFlash(__('The referees level has been deleted.'));
		} else {
			$this->Session->setFlash(__('The referees level could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
