<?php
App::uses('AppController', 'Controller');
/**
 * Referees Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property Referee $Referee
 */
class RefereesController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->Referee->recursive = 0;
		$this->set('referees', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->Referee->exists($id)) {
			throw new NotFoundException(__('Invalid referee'));
		}
		$options = array('conditions' => array('Referee.' . $this->Referee->primaryKey => $id));
		$this->set('referee', $this->Referee->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->Referee->create();
			if ($this->Referee->save($this->request->data)) {
				$this->Session->setFlash(__('The referee has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The referee could not be saved. Please, try again.'));
			}
		}
		$associations = $this->Referee->Association->find('list');
		$this->set(compact('associations'));
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->Referee->exists($id)) {
			throw new NotFoundException(__('Invalid referee'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->Referee->save($this->request->data)) {
				$this->Session->setFlash(__('The referee has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The referee could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('Referee.' . $this->Referee->primaryKey => $id));
			$this->request->data = $this->Referee->find('first', $options);
		}
		$associations = $this->Referee->Association->find('list');
        $accountings = $this->Referee->Accounting->findAllByIdentityNumberAndEntityType($id,'Referee');
        $remarksAry = $this->Referee->Remarks->findAllByIdentityNumberAndEntityType($id,'Referee');
        $refereesPayments = $this->request->data['RefereesPayment'] ;
        $refereesStudies  = $this->request->data['RefereesStudy'] ;
        // fix remarks array to suit remarks element
        foreach ($remarksAry as $key => $remark) {
            $remarks[] = $remark['Remarks']; 
        }
        
        
        
        
		$this->set(compact('associations','accountings','remarks','refereesPayments','refereesStudies'));
        
        
        
        
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->Referee->id = $id;
		if (!$this->Referee->exists()) {
			throw new NotFoundException(__('Invalid referee'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->Referee->delete()) {
			$this->Session->setFlash(__('The referee has been deleted.'));
		} else {
			$this->Session->setFlash(__('The referee could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
