<?php
App::uses('AppController', 'Controller');
/**
 * ScoringFormats Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property ScoringFormat $ScoringFormat
 */
class ScoringFormatsController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->ScoringFormat->recursive = 0;
		$this->set('scoringFormats', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->ScoringFormat->exists($id)) {
			throw new NotFoundException(__('Invalid scoring format'));
		}
		$options = array('conditions' => array('ScoringFormat.' . $this->ScoringFormat->primaryKey => $id));
		$this->set('scoringFormat', $this->ScoringFormat->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->ScoringFormat->create();
			if ($this->ScoringFormat->save($this->request->data)) {
				$this->Session->setFlash(__('The scoring format has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The scoring format could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->ScoringFormat->exists($id)) {
			throw new NotFoundException(__('Invalid scoring format'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->ScoringFormat->save($this->request->data)) {
				$this->Session->setFlash(__('The scoring format has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The scoring format could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('ScoringFormat.' . $this->ScoringFormat->primaryKey => $id));
			$this->request->data = $this->ScoringFormat->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->ScoringFormat->id = $id;
		if (!$this->ScoringFormat->exists()) {
			throw new NotFoundException(__('Invalid scoring format'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->ScoringFormat->delete()) {
			$this->Session->setFlash(__('The scoring format has been deleted.'));
		} else {
			$this->Session->setFlash(__('The scoring format could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
