<?php
App::uses('AppController', 'Controller');
/**
 * SpecialVacations Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property SpecialVacation $SpecialVacation
 */
class SpecialVacationsController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->SpecialVacation->recursive = 0;
		$this->set('specialVacations', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->SpecialVacation->exists($id)) {
			throw new NotFoundException(__('Invalid special vacation'));
		}
		$options = array('conditions' => array('SpecialVacation.' . $this->SpecialVacation->primaryKey => $id));
		$this->set('specialVacation', $this->SpecialVacation->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->SpecialVacation->create();
			if ($this->SpecialVacation->save($this->request->data)) {
				$this->Session->setFlash(__('The special vacation has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The special vacation could not be saved. Please, try again.'));
			}
		}
	}
    
   

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->SpecialVacation->exists($id)) {
			throw new NotFoundException(__('Invalid special vacation'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->SpecialVacation->save($this->request->data)) {
				$this->Session->setFlash(__('The special vacation has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The special vacation could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('SpecialVacation.' . $this->SpecialVacation->primaryKey => $id));
			$this->request->data = $this->SpecialVacation->find('first', $options);
		}
	}
    
    
    public function ajaxEdit($id = null) {
        $this->layout = "modal";
        if (!$this->SpecialVacation->exists($id)) {
            throw new NotFoundException(__('Invalid special vacation'));
        }
        if ($this->request->is('post') || $this->request->is('put')) {
            if ($this->SpecialVacation->save($this->request->data)) {
                $this->Session->setFlash(__('The special vacation has been saved'));
                return $this->redirect(array('action' => 'index'));
            } else {
                $this->Session->setFlash(__('The special vacation could not be saved. Please, try again.'));
            }
        } else {
            $options = array('conditions' => array('SpecialVacation.' . $this->SpecialVacation->primaryKey => $id));
            $this->request->data = $this->SpecialVacation->find('first', $options);
        }
      
       $this->set('modalHeader','עדכון חופשה');  
       
        
        
    }    

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->SpecialVacation->id = $id;
		if (!$this->SpecialVacation->exists()) {
			throw new NotFoundException(__('Invalid special vacation'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->SpecialVacation->delete()) {
			$this->Session->setFlash(__('The special vacation has been deleted.'));
		} else {
			$this->Session->setFlash(__('The special vacation could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
