<?php
App::uses('AppController', 'Controller');
/**
 * SysSettings Controller
 * Generated by Petit Four the online baking tool for CakePHP: http://patisserie.keensoftware.com
 * @property SysSetting $SysSetting
 */
class SysSettingsController extends AppController {

/**
 * index method
 *
 * @return void
 */
	public function index() {
		$this->SysSetting->recursive = 0;
		$this->set('sysSettings', $this->paginate());
	}

/**
 * view method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function view($id = null) {
		if (!$this->SysSetting->exists($id)) {
			throw new NotFoundException(__('Invalid sys setting'));
		}
		$options = array('conditions' => array('SysSetting.' . $this->SysSetting->primaryKey => $id));
		$this->set('sysSetting', $this->SysSetting->find('first', $options));
	}

/**
 * add method
 *
 * @return void
 */
	public function add() {
		if ($this->request->is('post')) {
			$this->SysSetting->create();
			if ($this->SysSetting->save($this->request->data)) {
				$this->Session->setFlash(__('The sys setting has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The sys setting could not be saved. Please, try again.'));
			}
		}
	}

/**
 * edit method
 *
 * @throws NotFoundException
 * @param int id
 * @return void
 */
	public function edit($id = null) {
		if (!$this->SysSetting->exists($id)) {
			throw new NotFoundException(__('Invalid sys setting'));
		}
		if ($this->request->is('post') || $this->request->is('put')) {
			if ($this->SysSetting->save($this->request->data)) {
				$this->Session->setFlash(__('The sys setting has been saved'));
				return $this->redirect(array('action' => 'index'));
			} else {
				$this->Session->setFlash(__('The sys setting could not be saved. Please, try again.'));
			}
		} else {
			$options = array('conditions' => array('SysSetting.' . $this->SysSetting->primaryKey => $id));
			$this->request->data = $this->SysSetting->find('first', $options);
		}
	}

/**
 * delete method
 *
 * @throws NotFoundException
 * @throws MethodNotAllowedException
 * @param int id
 * @return void
 */
	public function delete($id = null) {
		$this->SysSetting->id = $id;
		if (!$this->SysSetting->exists()) {
			throw new NotFoundException(__('Invalid sys setting'));
		}
		$this->request->onlyAllow('post', 'delete');
		if ($this->SysSetting->delete()) {
			$this->Session->setFlash(__('The sys setting has been deleted.'));
		} else {
			$this->Session->setFlash(__('The sys setting could not be deleted. Please, try again.'));
		}
		return $this->redirect(array('action' => 'index'));
	}
}
